### ISSUE TITLE
Corner hole dimension incorrect

### ISSUE THREAD

**Issue by oliver-rew** [shridattdudhat/Raspberry-Pi-Compute-Module-4-Eagle-Footprint#2]
I noticed one of the corner holes was incorrect

**Comment by shridattdudhat** [comment]
Hi, Thank you for pointing out and creating the issue, I'll fix that and commit the files

**Comment by shridattdudhat** [comment]
Right Upper Corner Hole Dimension fixed #2

Thank you @oliver-rew
