### ISSUE TITLE
are u try this real pcb ?

### ISSUE THREAD

**Issue by K0rkunc** [shridattdudhat/Raspberry-Pi-Compute-Module-4-Eagle-Footprint#3]
tryed this?

**Comment by robintk** [comment]
Yes.

**Comment by shridattdudhat** [comment]
Yes, the dimensions are perfect. 

![image](https://user-images.githubusercontent.com/28555587/119606587-7f558f80-be10-11eb-80a6-8cc0be9a030b.png)
