### ISSUE TITLE
Incorrect smd output

### ISSUE THREAD

**Issue by hackintoshlover** [shridattdudhat/Raspberry-Pi-Compute-Module-4-Eagle-Footprint#5]
Hi,
I designed my pcb using your library but when i do mount md in eagle, the output seems wrong.
Moreover feels like only one part is exported that too incorrect.
![Screenshot (76)](https://user-images.githubusercontent.com/40655406/136150196-dc459c7d-1c5c-453e-b0ef-c4ca0e4e07b4.png)
It should export two connectors right?
But it seems to export none.
Kindly help with this.

**Comment by shridattdudhat** [comment]
Hi @hackintoshlover 
Actually, I combined two connectors in One Library.

Let me check with this issue, I will update here, 
Thank you for pointing out the issue.
