### ISSUE TITLE
error

### ISSUE THREAD

**Issue by K0rkunc** [shridattdudhat/Raspberry-Pi-Compute-Module-4-Eagle-Footprint#6]
![image](https://user-images.githubusercontent.com/5460766/138544859-7c49c742-d0c8-4c59-825c-1f0b9a228dcd.png)

how to solve

**Comment by brentpicasso** [comment]
I am seeing this problem as well.  I am running the latest version of eagle, 9.6.2

**Comment by brentpicasso** [comment]
Commit bf0bfc4bc433c8a917c7d0e91c7a247ad591aaf6 seems to load correctly.

**Comment by shridattdudhat** [comment]
@K0rkunc Which version of Eagle are you using ??

The Library works perfectly on Eagle 9.6.2

![image](https://user-images.githubusercontent.com/28555587/144699730-83f9c98f-5b71-4ccc-9e38-f3ed1bda2979.png)

**Comment by K0rkunc** [comment]
Can u do re upload library ?? My eagle 9.6.2

**Comment by shridattdudhat** [comment]
[RPI-CM4.zip](https://github.com/shridattdudhat/Raspberry-Pi-Compute-Module-4-Eagle-Footprint/files/7653529/RPI-CM4.zip)
